/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Slaush
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        registrar = new javax.swing.JMenu();
        turista = new javax.swing.JMenuItem();
        Vuelo = new javax.swing.JMenuItem();
        hotel = new javax.swing.JMenuItem();
        sucursal = new javax.swing.JMenuItem();
        admin = new javax.swing.JMenuItem();
        asignar = new javax.swing.JMenu();
        viaje = new javax.swing.JMenuItem();
        hospedaje = new javax.swing.JMenuItem();
        contrato = new javax.swing.JMenuItem();
        Ver = new javax.swing.JMenu();
        turistas = new javax.swing.JMenuItem();
        hoteles = new javax.swing.JMenuItem();
        vuelos = new javax.swing.JMenuItem();
        sucursales = new javax.swing.JMenuItem();
        viajes = new javax.swing.JMenuItem();
        hospedajes = new javax.swing.JMenuItem();
        contrataciones = new javax.swing.JMenuItem();
        admins = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        registrar.setText("Registrar");

        turista.setText("Turista");
        registrar.add(turista);

        Vuelo.setText("Vuelo");
        Vuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VueloActionPerformed(evt);
            }
        });
        registrar.add(Vuelo);

        hotel.setText("Hotel");
        registrar.add(hotel);

        sucursal.setText("Sucursal");
        registrar.add(sucursal);

        admin.setText("Administrador");
        registrar.add(admin);

        jMenuBar1.add(registrar);

        asignar.setText("Asignar");

        viaje.setText("Viaje");
        asignar.add(viaje);

        hospedaje.setText("Hospedaje");
        asignar.add(hospedaje);

        contrato.setText("Contratacion");
        asignar.add(contrato);

        jMenuBar1.add(asignar);

        Ver.setText("Ver");

        turistas.setText("Turistas");
        Ver.add(turistas);

        hoteles.setText("Hoteles");
        Ver.add(hoteles);

        vuelos.setText("Vuelos");
        vuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vuelosActionPerformed(evt);
            }
        });
        Ver.add(vuelos);

        sucursales.setText("Sucursales");
        Ver.add(sucursales);

        viajes.setText("Viajes");
        Ver.add(viajes);

        hospedajes.setText("Hospedajes");
        Ver.add(hospedajes);

        contrataciones.setText("Contrataciones");
        Ver.add(contrataciones);

        admins.setText("Administradores");
        Ver.add(admins);

        jMenuBar1.add(Ver);

        logout.setText("Cerrar Sesion");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VueloActionPerformed

    private void vuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vuelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vuelosActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
    System.exit(0);
    }//GEN-LAST:event_logoutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Ver;
    public javax.swing.JMenuItem Vuelo;
    public javax.swing.JMenuItem admin;
    public javax.swing.JMenuItem admins;
    public javax.swing.JMenu asignar;
    public javax.swing.JMenuItem contrataciones;
    public javax.swing.JMenuItem contrato;
    public javax.swing.JMenuItem hospedaje;
    public javax.swing.JMenuItem hospedajes;
    public javax.swing.JMenuItem hotel;
    public javax.swing.JMenuItem hoteles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu logout;
    public javax.swing.JMenu registrar;
    public javax.swing.JMenuItem sucursal;
    public javax.swing.JMenuItem sucursales;
    public javax.swing.JMenuItem turista;
    public javax.swing.JMenuItem turistas;
    public javax.swing.JMenuItem viaje;
    public javax.swing.JMenuItem viajes;
    public javax.swing.JMenuItem vuelos;
    // End of variables declaration//GEN-END:variables
}
