/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package models;

// Generated 17-sep-2017 20:56:56 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import utils.Encrypter;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name="admins"
    ,schema="dbo"
    ,catalog="Viajes"   
)
public class Admin implements java.io.Serializable {
    
    
    private String username;
    private String password;
    
    public static final String [] properties = {"username"};
    public static final String [] asColumns = {"Cedula"};
    
    public Admin() {
    }

    public Admin(String username, String password) {
        this.username = username;
        this.password = Encrypter.encrypt(password);
    }
    
    @Id
    @Column(name="username", nullable=false)
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
}


