package models;
// Generated 17-sep-2017 20:56:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContratoId generated by hbm2java
 */
@Embeddable
public class ContratoId  implements java.io.Serializable {


     private String turista;
     private String sucursal;

    public ContratoId() {
    }

    public ContratoId(String turista, String sucursal) {
       this.turista = turista;
       this.sucursal = sucursal;
    }
   


    @Column(name="turista", nullable=false, length=36)
    public String getTurista() {
        return this.turista;
    }
    
    public void setTurista(String turista) {
        this.turista = turista;
    }


    @Column(name="sucursal", nullable=false, length=36)
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContratoId) ) return false;
		 ContratoId castOther = ( ContratoId ) other; 
         
		 return ( (this.getTurista()==castOther.getTurista()) || ( this.getTurista()!=null && castOther.getTurista()!=null && this.getTurista().equals(castOther.getTurista()) ) )
 && ( (this.getSucursal()==castOther.getSucursal()) || ( this.getSucursal()!=null && castOther.getSucursal()!=null && this.getSucursal().equals(castOther.getSucursal()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTurista() == null ? 0 : this.getTurista().hashCode() );
         result = 37 * result + ( getSucursal() == null ? 0 : this.getSucursal().hashCode() );
         return result;
   }   


}


