package models;
// Generated 17-sep-2017 20:56:56 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name="contratos"
    ,schema="dbo"
    ,catalog="Viajes"
    , uniqueConstraints = @UniqueConstraint(columnNames={"turista", "sucursal"}) 
)
public class Contrato  implements java.io.Serializable {


     private ContratoId id;
     private Sucursal sucursales;
     private Turista turistas;
     public static final String [] properties = {"sucursal","turista"};
     public static final String [] asColumns = {"Sucursal","Turista"};
    public Contrato() {
    }

    public Contrato(ContratoId id, Sucursal sucursales, Turista turistas) {
       this.id = id;
       this.sucursales = sucursales;
       this.turistas = turistas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="turista", column=@Column(name="turista", nullable=false, length=36) ), 
        @AttributeOverride(name="sucursal", column=@Column(name="sucursal", nullable=false, length=36) ) } )
    public ContratoId getId() {
        return this.id;
    }
    
    public void setId(ContratoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sucursal", nullable=false, insertable=false, updatable=false)
    public Sucursal getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursal sucursales) {
        this.sucursales = sucursales;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="turista", nullable=false, insertable=false, updatable=false)
    public Turista getTuristas() {
        return this.turistas;
    }
    
    public void setTuristas(Turista turistas) {
        this.turistas = turistas;
    }




}


