package models;
// Generated 17-sep-2017 20:56:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HospedajeId generated by hbm2java
 */
@Embeddable
public class HospedajeId  implements java.io.Serializable {


     private String turista;
     private String hotel;

    public HospedajeId() {
    }

    public HospedajeId(String turista, String hotel) {
       this.turista = turista;
       this.hotel = hotel;
    }
   


    @Column(name="turista", nullable=false, length=36)
    public String getTurista() {
        return this.turista;
    }
    
    public void setTurista(String turista) {
        this.turista = turista;
    }


    @Column(name="hotel", nullable=false, length=36)
    public String getHotel() {
        return this.hotel;
    }
    
    public void setHotel(String hotel) {
        this.hotel = hotel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HospedajeId) ) return false;
		 HospedajeId castOther = ( HospedajeId ) other; 
         
		 return ( (this.getTurista()==castOther.getTurista()) || ( this.getTurista()!=null && castOther.getTurista()!=null && this.getTurista().equals(castOther.getTurista()) ) )
 && ( (this.getHotel()==castOther.getHotel()) || ( this.getHotel()!=null && castOther.getHotel()!=null && this.getHotel().equals(castOther.getHotel()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTurista() == null ? 0 : this.getTurista().hashCode() );
         result = 37 * result + ( getHotel() == null ? 0 : this.getHotel().hashCode() );
         return result;
   }   


}


