package models;
// Generated 17-sep-2017 20:56:56 by Hibernate Tools 4.3.1


import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hospedaje generated by hbm2java
 */
@Entity
@Table(name="hospedajes"
    ,schema="dbo"
    ,catalog="Viajes"
)
public class Hospedaje  implements java.io.Serializable {


     private HospedajeId id;
     private Hotel hotel;
     private Turista turista;
     private String llegada;
     private String partida;
     
     public static final String [] properties = {"hotel","turista","llegada","partida"};
     public static final String [] asColumns = {"Hotel","Turista","Llegada","Partida"};
     
    public Hospedaje() {
    }

    public Hospedaje(Hotel hotel, Turista turista, String llegada, String partida) {
       this.id = new HospedajeId(turista.getId(),hotel.getId());
       this.hotel = hotel;
       this.turista = turista;
       this.llegada = llegada;
       this.partida = partida;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="turista", column=@Column(name="turista", nullable=false, length=36) ), 
        @AttributeOverride(name="hotel", column=@Column(name="hotel", nullable=false, length=36) ) } )
    public HospedajeId getId() {
        return this.id;
    }
    
    public void setId(HospedajeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hotel", nullable=false, insertable=false, updatable=false)
    public String getHotel() {
        return this.hotel.getNombre();
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="turista", nullable=false, insertable=false, updatable=false)
    public String getTurista() {
        return this.turista.getNombre() + this.turista.getApellido();
    }
    
    public void setTurista(Turista turista) {
        this.turista = turista;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="llegada", nullable=false, length=10)
    public String getLlegada() {
        return this.llegada.trim();
    }
    
    public void setLlegada(String llegada) {
        Date date = new Date(llegada);
        String newstring = new SimpleDateFormat("dd/MM/yyyy").format(date);
        this.llegada = newstring;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="partida", nullable=false, length=10)
    public String getPartida() {
        return this.partida.trim();
    }
    
    public void setPartida(String partida) {
        Date date = new Date(partida);
        String newstring = new SimpleDateFormat("dd/MM/yyyy").format(date);
        this.partida = newstring;
    }




}


