package models;
// Generated 17-sep-2017 20:56:56 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name="sucursales"
    ,schema="dbo"
    ,catalog="Viajes"
)
public class Sucursal  implements java.io.Serializable {

      
     private String id;
     private String direccion;
     private String telefono;

    public static final String [] properties = {"direccion","telefono"}; 
    public static final String [] asColumns = {"Direccion","Telefono"};
    public Sucursal() {
    }

	
    public Sucursal (String direccion, String telefono) {
        this.id = UUID.randomUUID().toString();
        this.direccion = direccion;
        this.telefono = telefono;
    }

    @Id
    @Column(name="id", unique=true, nullable=false, length=36)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="direccion", nullable=false)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", nullable=false)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
}


