package models;
// Generated 17-sep-2017 20:56:56 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Turista generated by hbm2java
 */
@Entity
@Table(name="turistas"
    ,schema="dbo"
    ,catalog="Viajes"
)
public class Turista  implements java.io.Serializable {

    private String id;
    private String nombre;
    private String apellido;
    private String direccion;
    private String telefono;
    
    public static final String [] properties = new String [] {"nombre", "apellido","direccion","telefono"};
    public static final String [] asColumns = new String [] {"Nombre", "Apellido", "Direccion", "Telefono"};
    
    public Turista() {
    }

	
    public Turista(String nombre, 
                   String apellido, String direccion, String telefono) {
        this.id = UUID.randomUUID().toString();
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.telefono = telefono;
    }

   
    @Id 
    @Column(name="id", unique=true, nullable=false, length=36)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre.trim();
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false)
    public String getApellido() {
        return this.apellido.trim();
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="direccion", nullable=false)
    public String getDireccion() {
        return this.direccion.trim();
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", nullable=false)
    public String getTelefono() {
        return this.telefono.trim();
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }



}


