package models;
// Generated 17-sep-2017 20:56:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViajesId generated by hbm2java
 */
@Embeddable
public class ViajesId  implements java.io.Serializable {


     private String turista;
     private String vuelo;

    public ViajesId() {
    }

    public ViajesId(String turista, String vuelo) {
       this.turista = turista;
       this.vuelo = vuelo;
    }
   


    @Column(name="turista", nullable=false, length=36)
    public String getTurista() {
        return this.turista;
    }
    
    public void setTurista(String turista) {
        this.turista = turista;
    }


    @Column(name="vuelo", nullable=false, length=36)
    public String getVuelo() {
        return this.vuelo;
    }
    
    public void setVuelo(String vuelo) {
        this.vuelo = vuelo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViajesId) ) return false;
		 ViajesId castOther = ( ViajesId ) other; 
         
		 return ( (this.getTurista()==castOther.getTurista()) || ( this.getTurista()!=null && castOther.getTurista()!=null && this.getTurista().equals(castOther.getTurista()) ) )
 && ( (this.getVuelo()==castOther.getVuelo()) || ( this.getVuelo()!=null && castOther.getVuelo()!=null && this.getVuelo().equals(castOther.getVuelo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTurista() == null ? 0 : this.getTurista().hashCode() );
         result = 37 * result + ( getVuelo() == null ? 0 : this.getVuelo().hashCode() );
         return result;
   }   


}


